#@ load("_helpers.star", "helpers")

#@ if helpers.is_pkg_enabled("cert-manager.tanzu.vmware.com"):
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager
  namespace: waas-install
  annotations:
    kapp.k14s.io/change-group: cert-manager
    kapp.k14s.io/change-rule: "delete before deleting serviceaccount"
spec:
  serviceAccountName: waas-install-sa
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: ">1.1.0"
      prereleases: {}
#@ end
