---
apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
 name: spring-sensors
 namespace: accelerator-system
spec:
 git:
   ref:
     branch: main
   url: https://github.com/cpage-pivotal/spring-sensors