#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("_helpers.star", "helpers")

#@ if helpers.is_pkg_enabled("eduk8s.vmware.com"):
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: eduk8s-operator
  namespace: waas-install
  annotations:
    kapp.k14s.io/change-group: eduk8s-operator
    kapp.k14s.io/change-rule.contour: "upsert after upserting contour" 
    kapp.k14s.io/change-rule.serviceaccount: "delete before deleting serviceaccount"
spec:
  serviceAccountName: waas-install-sa
  fetch:
  - git:
      url: https://github.com/eduk8s/eduk8s
      ref: origin/master
      subPath: resources
      lfsSkipSmudge: true
  template:
  - ytt: 
      ignoreUnknownComments: true
      inline:
        paths:
          deployment-overlay.yaml: |
            #@ load("@ytt:data", "data")
            #@ load("@ytt:overlay", "overlay")
            #@overlay/match by=overlay.subset({"apiVersion": "apps/v1", "kind": "Deployment", "metadata": {"name": "eduk8s-operator"}}), expects="1+"
            ---
            spec:
              template:
                spec:
                  containers:
                  #@overlay/match by=overlay.map_key("name")
                  - name: eduk8s
                    imagePullPolicy: IfNotPresent
                    #@overlay/match missing_ok=True
                    env:
                    - name: INGRESS_DOMAIN
                      value: #@ data.values.ingress_domain
                    - name: INGRESS_SECRET
                      value: eduk8s-cert-tls
          cluster-role-binding-overlay.yaml: |
            #@ load("@ytt:overlay", "overlay")
            #@overlay/match by=overlay.subset({"apiVersion": "rbac.authorization.k8s.io/v1", "kind": "ClusterRoleBinding", "metadata": {"name": "eduk8s-cluster-admin"}}), expects="1+"
            ---
            subjects:
            #@overlay/match by=overlay.map_key("name")
            - kind: ServiceAccount
              name: eduk8s
              #@overlay/match missing_ok=True
              namespace: eduk8s
      paths:
      - crds-v1
      - operator
      valuesFrom:
      - secretRef:
          name: eduk8s-values
  deploy:
  - kapp:
      intoNs: eduk8s
---
apiVersion: v1
kind: Secret
metadata:
  name: eduk8s-values
  namespace: waas-install
stringData:
  values.yaml: #@ yaml.encode(data.values.eduk8s)
#@ end