#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kapp.k14s.io/change-group: harbor-project-controller
    kapp.k14s.io/change-rule.cert-manager: "upsert after upserting metacontroller" 
    kapp.k14s.io/change-rule.serviceaccount: "delete before deleting serviceaccount"
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: gitea-overlay
  name: gitea
  namespace: waas-install
spec:
  packageRef:
    refName: gitea.vmware.com
    versionSelection:
      constraints: 1.15.3+0
      prereleases: {}
  serviceAccountName: waas-install-sa
  values:
  - secretRef:
      name: gitea-values
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-values
  namespace: waas-install
stringData:
  values.yaml: #@ yaml.encode(data.values.gitea)
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-overlay
  namespace: waas-install
stringData:
  secret-import.yaml: |
    ---
    apiVersion: secretgen.carvel.dev/v1alpha1
    kind: SecretImport
    metadata:
      name: eduk8s-cert-tls
      namespace: gitea
    spec:
      fromNamespace: waas-install