#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("_helpers.star", "helpers")

#@ if helpers.is_pkg_enabled("harbor.tanzu.vmware.com"):
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kapp.k14s.io/change-group: harbor
    kapp.k14s.io/change-rule.contour: "upsert after upserting contour" 
    kapp.k14s.io/change-rule.serviceaccount: "delete before deleting serviceaccount"
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: harbor-notary-overlay
  name: harbor
  namespace: waas-install
spec:
  packageRef:
    refName: harbor.tanzu.vmware.com
    versionSelection:
      constraints: 2.2.3+vmware.1-tkg.1
      prereleases: {}
  serviceAccountName: waas-install-sa
  values:
  - secretRef:
      name: harbor-values
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-values
  namespace: waas-install
stringData:
  values.yaml: #@ yaml.encode(data.values.harbor)
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-notary-overlay
  namespace: waas-install
stringData:
  overlay-notary-signer-image-fix.yaml: |
    #@ load("@ytt:overlay", "overlay")

    #@overlay/match by=overlay.and_op(overlay.subset({"kind": "Deployment"}), overlay.subset({"metadata": {"name": "harbor-notary-signer"}}))
    ---
    spec:
      template:
        spec:
          containers:
            #@overlay/match by="name",expects="0+"
            - name: notary-signer
              image: projects.registry.vmware.com/tkg/harbor/notary-signer-photon@sha256:4dfbf3777c26c615acfb466b98033c0406766692e9c32f3bb08873a0295e24d1
  httpproxy-tls.yaml: |
    #@ load("@ytt:overlay", "overlay")

    #@overlay/match by=overlay.and_op(overlay.subset({"kind": "HTTPProxy"}), overlay.or_op(overlay.subset({"metadata": {"name": "harbor-httpproxy"}}), overlay.subset({"metadata": {"name": "harbor-httpproxy-notary"}}))), expects="2+"
    ---
    spec:
      virtualhost:
        tls:
          secretName: eduk8s/eduk8s-cert-tls
#@ end