#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("_helpers.star", "helpers")

#@ if helpers.is_pkg_enabled("le-certmanager.vmware.com"):
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: le-certmanager
  namespace: waas-install
  annotations:
    kapp.k14s.io/change-group: le-certmanager
    kapp.k14s.io/change-rule.cert-manager: "upsert after upserting cert-manager" 
    kapp.k14s.io/change-rule.serviceaccount: "delete before deleting serviceaccount"
spec:
  serviceAccountName: waas-install-sa
  packageRef:
    refName: le-certmanager.vmware.com
    versionSelection:
      constraints: "1.0.0"
      prereleases: {}
  values:
  - secretRef:
      name: le-certmanager-values
---
apiVersion: v1
kind: Secret
metadata:
  name: le-certmanager-values
  namespace: waas-install
stringData:
  values.yaml: #@ yaml.encode(data.values.le_certmanager)
#@ end

