#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-rabbitmq-repo
  namespace: waas-install
spec:
  fetch:
    imgpkgBundle:
      image: harbor.workshop.amer.end2end.link/registry-tanzu/tanzu-rabbitmq-package-repo:1.2.0
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tanzu-rabbitmq
spec:
  serviceAccountName: waas-install-sa
  packageRef:
    refName: rabbitmq.tanzu.vmware.com
    versionSelection:
      constraints: "1.2.0"