---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: secretgen-controller-tkg-system-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: secretgen-controller-tkg-system-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: secretgen-controller-tkg-system-sa
  creationTimestamp: "2022-02-24T22:54:29Z"
  finalizers:
  - finalizers.packageinstall.packaging.carvel.dev/delete
  generation: 1
  name: secretgen-controller
  namespace: tkg-system
  resourceVersion: "15916234"
  uid: 316bb69e-60ef-418a-8b47-b705face6734
spec:
  packageRef:
    refName: secretgen-controller.tanzu.vmware.com
    versionSelection:
      constraints: ">0.7.1"
      prereleases: {}
  serviceAccountName: secretgen-controller-tkg-system-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: secretgen-controller-tkg-system
  name: secretgen-controller-tkg-system-sa
  namespace: tkg-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: secretgen-controller-tkg-system
  name: secretgen-controller-tkg-system-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: secretgen-controller-tkg-system
  name: secretgen-controller-tkg-system-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secretgen-controller-tkg-system-cluster-role
subjects:
- kind: ServiceAccount
  name: secretgen-controller-tkg-system-sa
  namespace: tkg-system