#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Namespace
metadata:
  name: tap-install
---
apiVersion: v1
stringData:
  #@yaml/text-templated-strings
  .dockerconfigjson: |
    {"auths":{"registry.tanzu.vmware.com":{"username":"(@= data.values.tap.buildservice.tanzunet_username @)","password":"(@= data.values.tap.buildservice.tanzunet_password @)"}}}
kind: Secret
metadata:
  name: tap-registry
  namespace: tap-install
type: kubernetes.io/dockerconfigjson
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tap-registry
  namespace: tap-install
spec:
  toNamespaces:
  - '*'
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  finalizers:
  - finalizers.packagerepository.packaging.carvel.dev/delete
  name: tanzu-tap-repository
  namespace: tap-install
spec:
  fetch:
    imgpkgBundle:
      image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages:1.0.1
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kapp.k14s.io/change-group: tap
    kapp.k14s.io/change-rule.contour: "upsert after upserting tap-harbor-project" 
    kapp.k14s.io/change-rule.serviceaccount: "delete before deleting tap-harbor-project"
  name: tap-full
  namespace: tap-install
spec:
  packageRef:
    refName: tap.tanzu.vmware.com
    versionSelection:
      constraints: "1.0.1"
      prereleases: {}
  serviceAccountName: tap-install-sa
  values:
  - secretRef:
      name: tap-values
---
apiVersion: v1
kind: Secret
metadata:
  name: tap-values
  namespace: tap-install
stringData:
  values.yaml: #@ yaml.encode(data.values.tap)