#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Namespace
metadata:
  name: purge-git
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin
  namespace: purge-git
stringData:
  gitea_admin_password: #@ data.values.waas_catalog.gitea.adminPassword
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: purge-gitops-deliverables
  namespace: purge-git
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - ./purge-git.sh gitops-workloads; ./purge-git.sh gitops-deliverables
            env:
            - name: GITEA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitea-admin
                  key: gitea_admin_password
                  optional: false
            - name: INGRESS_DOMAIN
              value: #@ data.values.gitea.ingress_domain
            - name: NUM_DAYS
              value: "1"
            image: harbor.workshop.amer.end2end.link/tanzu-e2e/purge-gitrepo:latest
            name: purge
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0 * * * *
  successfulJobsHistoryLimit: 3
