#@data/values-schema
---
#! e.g. "cert-manager.vmware.com"
excluded_packages:
- ""

#@schema/type any=True
contour: {}

#@schema/type any=True
external_dns: {}

external_dns_extras:
  aws_access_key_id: ""
  aws_secret_access_key: ""

#@schema/type any=True
le_certmanager: {}

#@schema/type any=True
harbor: {}

#@schema/type any=True
eduk8s: {}

#@schema/type any=True
eduk8s_cert: {}

#@schema/type any=True
harbor_project_controller: {}

#@schema/type any=True
waas_catalog: {}

#@schema/type any=True
tap: {}

gitea:
  ingress_domain: ""
  ingress_secret: ""
  extra_repository_config: ""
  admin_username: "gitea_admin"
  admin_password: ""

devnexus:
  passcode: ""

trainingportal_janitor:
  pull_secret:
    username: ""
    password: ""

waas_portal:
  client_id: ""
  client_secret: ""